### ISSUE TITLE
Error on disconnect

### ISSUE THREAD

**Issue by ceholden** [ceholden/TSTools#67]
When using the `LayerStackedTimeseries` driver (e.g., one without results to plot), users see this on exiting QGIS / removing plugin:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/qgis-28/2.8.3/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 270, in unloadPlugin
    plugins[packageName].unload()
  File "/Users/Eric/.qgis2/python/plugins/tstools/tstools.py", line 160, in unload
    self.controller.disconnect()
  File "/Users/Eric/.qgis2/python/plugins/tstools/controller.py", line 710, in disconnect
    self.controls.disconnect()
  File "/Users/Eric/.qgis2/python/plugins/tstools/controls/controls.py", line 538, in disconnect
    self.cbox_modelfit.stateChanged.disconnect()
TypeError: disconnect() failed between 'stateChanged' and all its connections

Python version:
2.7.10 (default, Aug 22 2015, 20:33:39) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)]


QGIS version:
2.8.3-Wien Wien, exported

Python path: ...
```

Sounds like I should:
1) Check to make sure it is connected (e.g., has results)
2) Wrap disconnect in try/except so users aren't bothered with error.

**Comment by ceholden** [comment]
Fixed!
